name: Testing My Node App

on:
  push:
  pull_request:
    branches: 
      - "main"
      - feature/*

jobs:
   test:
     runs-on: ubuntu-latest
     strategy:
        matrix:
         node-version: ["20.x", "18.x"]

     steps:
       - uses: "actions/checkout@v4"
       - name: Running all my app test
         uses: "actions/setup-node@v4"
         with:
          node-version: "20.x"

       - run: |
            echo "We will be running the test defined in the project itself"
            echo "Sit back, relax and enjoy the ride" fi

       - name: Installing Devepencies
         run: npm ci
       - name: Testing my node app
         run: npm run test
         
          
           
         

    
     
